"""Допустимые slug категорий событий (не путать с интересами профиля)."""

from __future__ import annotations

_NEW: frozenset[str] = frozenset(
    {
        "music_events",
        "sport_outdoor",
        "food_tasting",
        "board_games_night",
        "cinema_club",
        "theater_goers",
        "photo_walk",
        "running_group",
        "yoga_morning",
        "tech_meetup",
        "startup_pitch",
        "books_club",
        "languages_exchange",
        "volunteer_day",
        "pet_meetup",
        "hiking_weekend",
        "museum_tour",
        "concert_live",
        "dance_social",
        "fitness_workout",
        "board_creativity",
        "esports_lan",
        "astronomy_night",
        "city_quest",
        "karaoke_night",
        "camping_trip",
        "masterclass_cooking",
        "art_workshop",
        "meditation_group",
        "cycling_ride",
        "charity_run",
        "quiz_night",
        "open_air",
        "jazz_session",
        "crafts_fair",
        "science_cafe",
        "history_walk",
        "comedy_standup",
        "fashion_swap",
        "wine_tasting",
        "kids_play",
    }
)

_LEGACY_INTEREST_SLUGS: frozenset[str] = frozenset(
    {
        "music",
        "sport",
        "travel",
        "movies",
        "books",
        "games",
        "photo",
        "cooking",
        "tech",
        "science",
        "art",
        "dance",
        "theater",
        "volunteer",
        "pets",
        "nature",
        "fitness",
        "yoga",
        "boardgames",
        "startup",
        "invest",
        "design",
        "languages",
        "history",
        "board_ski",
        "hiking",
        "board_water",
        "board_motor",
        "board_astronomy",
        "board_esports",
    }
)

EVENT_CATEGORY_SLUGS = _NEW | _LEGACY_INTEREST_SLUGS
