import type { ComponentType, SVGProps } from 'react'
import {
  AcademicCapIcon,
  BeakerIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingOffice2Icon,
  CakeIcon,
  CameraIcon,
  ChartBarIcon,
  CircleStackIcon,
  CloudIcon,
  CommandLineIcon,
  CpuChipIcon,
  CubeIcon,
  FilmIcon,
  FireIcon,
  FlagIcon,
  GiftIcon,
  GlobeAmericasIcon,
  GlobeEuropeAfricaIcon,
  HandRaisedIcon,
  HeartIcon,
  HomeModernIcon,
  LanguageIcon,
  LifebuoyIcon,
  LightBulbIcon,
  MicrophoneIcon,
  MoonIcon,
  MusicalNoteIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PauseCircleIcon,
  PencilSquareIcon,
  PuzzlePieceIcon,
  RectangleGroupIcon,
  RocketLaunchIcon,
  ScaleIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  SwatchIcon,
  TicketIcon,
  TruckIcon,
  TrophyIcon,
  TvIcon,
  UserGroupIcon,
  UsersIcon,
  ViewfinderCircleIcon,
  WrenchScrewdriverIcon,
} from '@heroicons/react/24/solid'

type SvgIcon = ComponentType<SVGProps<SVGSVGElement>>

const BY_SLUG: Record<string, SvgIcon> = {
  music: MusicalNoteIcon,
  sport: TrophyIcon,
  travel: PaperAirplaneIcon,
  movies: FilmIcon,
  books: BookOpenIcon,
  games: PuzzlePieceIcon,
  photo: CameraIcon,
  cooking: CakeIcon,
  tech: CpuChipIcon,
  science: BeakerIcon,
  art: PaintBrushIcon,
  dance: UserGroupIcon,
  theater: TicketIcon,
  volunteer: HandRaisedIcon,
  pets: HeartIcon,
  nature: GlobeAmericasIcon,
  fitness: BoltIcon,
  yoga: MoonIcon,
  boardgames: CubeIcon,
  startup: RocketLaunchIcon,
  invest: ChartBarIcon,
  design: SwatchIcon,
  languages: LanguageIcon,
  history: AcademicCapIcon,
  board_ski: CloudIcon,
  hiking: ViewfinderCircleIcon,
  board_water: LifebuoyIcon,
  board_motor: TruckIcon,
  board_astronomy: StarIcon,
  board_esports: CommandLineIcon,
  fashion: ShoppingBagIcon,
  beauty: SunIcon,
  gardening: HomeModernIcon,
  crypto: CircleStackIcon,
  blogging: PencilSquareIcon,
  podcast: MicrophoneIcon,
  anime: TvIcon,
  diy: WrenchScrewdriverIcon,
  chess: RectangleGroupIcon,
  sailing: GlobeEuropeAfricaIcon,
  architecture: BuildingOffice2Icon,
  medicine: ShieldCheckIcon,
  education: AcademicCapIcon,
  parenting: UsersIcon,
  law: ScaleIcon,
  psychology: LightBulbIcon,
  esoteric: FireIcon,
  wine: GiftIcon,
  board_fishing: FlagIcon,
  board_meditation: PauseCircleIcon,
}

type Props = {
  slug: string
  className?: string
}

export function InterestHeroIcon({ slug, className }: Props) {
  const Cmp = BY_SLUG[slug] ?? SparklesIcon
  return <Cmp className={className} aria-hidden />
}
